### ISSUE TITLE
Ajout fichier musique

### ISSUE THREAD

**Issue by LeaHuong** [HE-Arc/Musiarc#2]
Formulaire d'ajout de musique

**Comment by rei152** [comment]
Bug "Path file has an extension that does not match its contents" observé cette après-midi.

Ce problème ne vient pas de nous ou du fichier audio mais de paperclip.
Descendu à la version 3.5.3 et ... ça marche!

Ref
http://stackoverflow.com/questions/21912322/ruby-on-rails-paperclip-error/21912537#21912537
